/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ey.se360_termproject_bcrs;

import com.bulenkov.darcula.DarculaLaf;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author Erel
 */
public class Bar extends javax.swing.JFrame {

    /**
     * Creates new form Bar
     */
    public Bar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BarMainTabbedPane = new javax.swing.JTabbedPane();
        MainTableTab = new javax.swing.JPanel();
        Table1Button = new javax.swing.JButton();
        ManagementTab = new javax.swing.JPanel();
        ManagementTabbedPane = new javax.swing.JTabbedPane();
        CategoryTab = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        CategoryList = new javax.swing.JList<>();
        CategoryIDLabel = new javax.swing.JLabel();
        CategoryNameLabel = new javax.swing.JLabel();
        CategoryDescriptionLabel = new javax.swing.JLabel();
        CategoryIDTextField = new javax.swing.JTextField();
        CategoryNameTextField = new javax.swing.JTextField();
        JScrollPane = new javax.swing.JScrollPane();
        CategoryDescriptionTextArea = new javax.swing.JTextArea();
        CategoryIDLabel1 = new javax.swing.JLabel();
        CategoryCreateButton = new javax.swing.JButton();
        CategoryRemoveButton = new javax.swing.JButton();
        CategoryUpdateButton = new javax.swing.JButton();
        CategoryTypeComboBox = new javax.swing.JComboBox<>();
        ProductTab = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        ProductList = new javax.swing.JList<>();
        ProductIDLabel = new javax.swing.JLabel();
        ProductNameLabel = new javax.swing.JLabel();
        ProductDescriptionLabel = new javax.swing.JLabel();
        ProductIDTextField = new javax.swing.JTextField();
        ProductNameTextFİeld = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        ProductDescriptionTextArea = new javax.swing.JTextArea();
        ProductPriceLabel = new javax.swing.JLabel();
        ProductPriceTextField = new javax.swing.JTextField();
        ProductCategoryLabel = new javax.swing.JLabel();
        ProductCategoryComboBox = new javax.swing.JComboBox<>();
        ProductAddButton = new javax.swing.JButton();
        ProductRemoveButton = new javax.swing.JButton();
        ProductUpdateButton = new javax.swing.JButton();
        ProductBrandLabel = new javax.swing.JLabel();
        ProductBrandTextField = new javax.swing.JTextField();
        ProductAlcoholVolumeLabel = new javax.swing.JLabel();
        ProductAlcoholVolumeTextField = new javax.swing.JTextField();
        WaiterTab = new javax.swing.JPanel();
        jScrollPane7 = new javax.swing.JScrollPane();
        WaiterList = new javax.swing.JList<>();
        WaiterIDLabel = new javax.swing.JLabel();
        WaiterNameLabel = new javax.swing.JLabel();
        WaiterIDTextField = new javax.swing.JTextField();
        WaiterNameTextField = new javax.swing.JTextField();
        WaiterAddButton = new javax.swing.JButton();
        WaiterRemoveButton = new javax.swing.JButton();
        WaiterUpdateButton = new javax.swing.JButton();
        WaiterSSNLabel = new javax.swing.JLabel();
        WaiterSSNTextField = new javax.swing.JTextField();
        WaiterPhoneNumberLabel = new javax.swing.JLabel();
        WaiterPhoneNumberTextField = new javax.swing.JTextField();
        TableTab = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        TableList = new javax.swing.JList<>();
        TableAddButton = new javax.swing.JButton();
        TableRemoveButton = new javax.swing.JButton();
        TableShortCodeLabel = new javax.swing.JLabel();
        TableShortCodeTextField = new javax.swing.JTextField();
        TableNameLabel = new javax.swing.JLabel();
        TableNameTextField = new javax.swing.JTextField();
        TableIDLabel = new javax.swing.JLabel();
        TableIDTextField = new javax.swing.JTextField();
        TableUpdateButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(700, 700));
        setResizable(false);

        BarMainTabbedPane.setTabPlacement(javax.swing.JTabbedPane.LEFT);

        MainTableTab.setLayout(new java.awt.GridLayout(3, 0));

        Table1Button.setText("jButton1");
        Table1Button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Table1ButtonMouseClicked(evt);
            }
        });
        MainTableTab.add(Table1Button);

        BarMainTabbedPane.addTab("Table", MainTableTab);

        ManagementTabbedPane.setMinimumSize(new java.awt.Dimension(700, 700));
        ManagementTabbedPane.setPreferredSize(new java.awt.Dimension(700, 700));

        jScrollPane1.setViewportView(CategoryList);

        CategoryIDLabel.setText("ID");
        CategoryIDLabel.setToolTipText("");

        CategoryNameLabel.setText("Name");

        CategoryDescriptionLabel.setText("Description");

        CategoryIDTextField.setEditable(false);

        CategoryDescriptionTextArea.setColumns(20);
        CategoryDescriptionTextArea.setRows(5);
        JScrollPane.setViewportView(CategoryDescriptionTextArea);

        CategoryIDLabel1.setText("Type");
        CategoryIDLabel1.setToolTipText("");

        CategoryCreateButton.setText("Add");
        CategoryCreateButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CategoryCreateButtonMouseClicked(evt);
            }
        });

        CategoryRemoveButton.setText("Remove");
        CategoryRemoveButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CategoryRemoveButtonMouseClicked(evt);
            }
        });

        CategoryUpdateButton.setText("Update");
        CategoryUpdateButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CategoryUpdateButtonMouseClicked(evt);
            }
        });

        CategoryTypeComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CategoryTypeComboBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout CategoryTabLayout = new javax.swing.GroupLayout(CategoryTab);
        CategoryTab.setLayout(CategoryTabLayout);
        CategoryTabLayout.setHorizontalGroup(
            CategoryTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CategoryTabLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(CategoryTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CategoryTabLayout.createSequentialGroup()
                        .addGroup(CategoryTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(CategoryTabLayout.createSequentialGroup()
                                .addComponent(CategoryNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(CategoryNameTextField))
                            .addGroup(CategoryTabLayout.createSequentialGroup()
                                .addComponent(CategoryDescriptionLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(JScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE)))
                        .addGap(6, 6, 6))
                    .addGroup(CategoryTabLayout.createSequentialGroup()
                        .addComponent(CategoryIDLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(CategoryIDTextField))
                    .addGroup(CategoryTabLayout.createSequentialGroup()
                        .addComponent(CategoryRemoveButton)
                        .addGap(66, 66, 66)
                        .addComponent(CategoryUpdateButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(CategoryCreateButton)
                        .addContainerGap())
                    .addGroup(CategoryTabLayout.createSequentialGroup()
                        .addComponent(CategoryIDLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(CategoryTypeComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        CategoryTabLayout.setVerticalGroup(
            CategoryTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CategoryTabLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1))
            .addGroup(CategoryTabLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(CategoryTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CategoryIDLabel)
                    .addComponent(CategoryIDTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(CategoryTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CategoryNameLabel)
                    .addComponent(CategoryNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(70, 70, 70)
                .addGroup(CategoryTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CategoryIDLabel1)
                    .addComponent(CategoryTypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(CategoryTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CategoryTabLayout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(JScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(CategoryTabLayout.createSequentialGroup()
                        .addGap(149, 149, 149)
                        .addComponent(CategoryDescriptionLabel)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 180, Short.MAX_VALUE)
                .addGroup(CategoryTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CategoryUpdateButton)
                    .addComponent(CategoryRemoveButton)
                    .addComponent(CategoryCreateButton))
                .addContainerGap())
        );

        ManagementTabbedPane.addTab("Categories", CategoryTab);

        jScrollPane3.setViewportView(ProductList);

        ProductIDLabel.setText("ID");
        ProductIDLabel.setToolTipText("");

        ProductNameLabel.setText("Name");

        ProductDescriptionLabel.setText("Description");

        ProductIDTextField.setEnabled(false);

        ProductNameTextFİeld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProductNameTextFİeldActionPerformed(evt);
            }
        });

        ProductDescriptionTextArea.setColumns(20);
        ProductDescriptionTextArea.setRows(5);
        jScrollPane4.setViewportView(ProductDescriptionTextArea);

        ProductPriceLabel.setText("Price");
        ProductPriceLabel.setToolTipText("");

        ProductPriceTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProductPriceTextFieldActionPerformed(evt);
            }
        });

        ProductCategoryLabel.setText("Category");

        ProductCategoryComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        ProductAddButton.setText("Add");
        ProductAddButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ProductAddButtonMouseClicked(evt);
            }
        });
        ProductAddButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProductAddButtonActionPerformed(evt);
            }
        });

        ProductRemoveButton.setText("Remove");
        ProductRemoveButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ProductRemoveButtonMouseClicked(evt);
            }
        });

        ProductUpdateButton.setText("Update");
        ProductUpdateButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ProductUpdateButtonMouseClicked(evt);
            }
        });

        ProductBrandLabel.setText("Brand");

        ProductAlcoholVolumeLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ProductAlcoholVolumeLabel.setText("Alcohol Volume");
        ProductAlcoholVolumeLabel.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        javax.swing.GroupLayout ProductTabLayout = new javax.swing.GroupLayout(ProductTab);
        ProductTab.setLayout(ProductTabLayout);
        ProductTabLayout.setHorizontalGroup(
            ProductTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ProductTabLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ProductTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ProductTabLayout.createSequentialGroup()
                        .addGroup(ProductTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(ProductTabLayout.createSequentialGroup()
                                .addComponent(ProductCategoryLabel)
                                .addGap(31, 31, 31))
                            .addGroup(ProductTabLayout.createSequentialGroup()
                                .addComponent(ProductNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(33, 33, 33))
                            .addGroup(ProductTabLayout.createSequentialGroup()
                                .addComponent(ProductIDLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(33, 33, 33)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(ProductTabLayout.createSequentialGroup()
                        .addGroup(ProductTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ProductPriceLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ProductBrandLabel)
                            .addComponent(ProductAlcoholVolumeLabel)
                            .addComponent(ProductRemoveButton)
                            .addComponent(ProductDescriptionLabel))
                        .addGap(33, 43, Short.MAX_VALUE)))
                .addGroup(ProductTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ProductTabLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(ProductUpdateButton)
                        .addGap(92, 92, 92)
                        .addComponent(ProductAddButton))
                    .addGroup(ProductTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(ProductBrandTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
                        .addComponent(ProductAlcoholVolumeTextField)
                        .addComponent(ProductNameTextFİeld)
                        .addComponent(ProductCategoryComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane4)
                        .addComponent(ProductPriceTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
                        .addComponent(ProductIDTextField)))
                .addGap(6, 6, 6))
        );
        ProductTabLayout.setVerticalGroup(
            ProductTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ProductTabLayout.createSequentialGroup()
                .addGroup(ProductTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ProductTabLayout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addGroup(ProductTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ProductIDLabel)
                            .addComponent(ProductIDTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(ProductTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ProductNameLabel)
                            .addComponent(ProductNameTextFİeld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addGroup(ProductTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ProductCategoryComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ProductCategoryLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                        .addGroup(ProductTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(ProductTabLayout.createSequentialGroup()
                                .addGap(64, 64, 64)
                                .addComponent(ProductDescriptionLabel)))
                        .addGap(18, 18, 18)
                        .addGroup(ProductTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ProductPriceLabel)
                            .addComponent(ProductPriceTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(ProductTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ProductBrandLabel)
                            .addComponent(ProductBrandTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(ProductTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ProductAlcoholVolumeLabel)
                            .addComponent(ProductAlcoholVolumeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(237, 237, 237)
                        .addGroup(ProductTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ProductAddButton)
                            .addComponent(ProductRemoveButton)
                            .addComponent(ProductUpdateButton)))
                    .addGroup(ProductTabLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane3)))
                .addContainerGap())
        );

        ManagementTabbedPane.addTab("Products", ProductTab);

        jScrollPane7.setViewportView(WaiterList);

        WaiterIDLabel.setText("ID");
        WaiterIDLabel.setToolTipText("");

        WaiterNameLabel.setText("Name");

        WaiterIDTextField.setEnabled(false);

        WaiterNameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WaiterNameTextFieldActionPerformed(evt);
            }
        });

        WaiterAddButton.setText("Add");
        WaiterAddButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                WaiterAddButtonMouseClicked(evt);
            }
        });

        WaiterRemoveButton.setText("Remove");
        WaiterRemoveButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                WaiterRemoveButtonMouseClicked(evt);
            }
        });

        WaiterUpdateButton.setText("Update");
        WaiterUpdateButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                WaiterUpdateButtonMouseClicked(evt);
            }
        });

        WaiterSSNLabel.setText("SSN");

        WaiterSSNTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WaiterSSNTextFieldActionPerformed(evt);
            }
        });

        WaiterPhoneNumberLabel.setText("Phone Number");

        WaiterPhoneNumberTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WaiterPhoneNumberTextFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout WaiterTabLayout = new javax.swing.GroupLayout(WaiterTab);
        WaiterTab.setLayout(WaiterTabLayout);
        WaiterTabLayout.setHorizontalGroup(
            WaiterTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(WaiterTabLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(WaiterTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(WaiterTabLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(WaiterTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(WaiterIDLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(WaiterNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(WaiterSSNLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(WaiterPhoneNumberLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(WaiterTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(WaiterIDTextField)
                            .addComponent(WaiterNameTextField)
                            .addComponent(WaiterSSNTextField)
                            .addComponent(WaiterPhoneNumberTextField)))
                    .addGroup(WaiterTabLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(WaiterRemoveButton)
                        .addGap(84, 84, 84)
                        .addComponent(WaiterUpdateButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 78, Short.MAX_VALUE)
                        .addComponent(WaiterAddButton)))
                .addContainerGap())
        );
        WaiterTabLayout.setVerticalGroup(
            WaiterTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(WaiterTabLayout.createSequentialGroup()
                .addGroup(WaiterTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(WaiterTabLayout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addGroup(WaiterTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(WaiterIDLabel)
                            .addComponent(WaiterIDTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(WaiterTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(WaiterNameLabel)
                            .addComponent(WaiterNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(WaiterTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(WaiterSSNLabel)
                            .addComponent(WaiterSSNTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(WaiterTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(WaiterPhoneNumberLabel)
                            .addComponent(WaiterPhoneNumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 452, Short.MAX_VALUE)
                        .addGroup(WaiterTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(WaiterRemoveButton)
                            .addComponent(WaiterUpdateButton)
                            .addComponent(WaiterAddButton)))
                    .addComponent(jScrollPane7))
                .addContainerGap())
        );

        ManagementTabbedPane.addTab("Waiters", WaiterTab);

        jScrollPane6.setViewportView(TableList);

        TableAddButton.setText("Add");
        TableAddButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableAddButtonMouseClicked(evt);
            }
        });

        TableRemoveButton.setText("Remove");

        TableShortCodeLabel.setText("Short Code");

        TableNameLabel.setText("Name");

        TableNameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TableNameTextFieldActionPerformed(evt);
            }
        });

        TableIDLabel.setText("ID");

        TableIDTextField.setEditable(false);

        TableUpdateButton.setText("Update");
        TableUpdateButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableUpdateButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout TableTabLayout = new javax.swing.GroupLayout(TableTab);
        TableTab.setLayout(TableTabLayout);
        TableTabLayout.setHorizontalGroup(
            TableTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TableTabLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(TableTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(TableTabLayout.createSequentialGroup()
                        .addComponent(TableRemoveButton)
                        .addGap(80, 80, 80)
                        .addComponent(TableUpdateButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 84, Short.MAX_VALUE)
                        .addComponent(TableAddButton))
                    .addGroup(TableTabLayout.createSequentialGroup()
                        .addComponent(TableNameLabel)
                        .addGap(90, 90, 90)
                        .addComponent(TableNameTextField))
                    .addGroup(TableTabLayout.createSequentialGroup()
                        .addComponent(TableShortCodeLabel)
                        .addGap(60, 60, 60)
                        .addComponent(TableShortCodeTextField))
                    .addGroup(TableTabLayout.createSequentialGroup()
                        .addComponent(TableIDLabel)
                        .addGap(112, 112, 112)
                        .addComponent(TableIDTextField)))
                .addContainerGap())
        );
        TableTabLayout.setVerticalGroup(
            TableTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TableTabLayout.createSequentialGroup()
                .addGroup(TableTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(TableTabLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(TableTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TableIDLabel)
                            .addComponent(TableIDTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addGroup(TableTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TableShortCodeLabel)
                            .addComponent(TableShortCodeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(TableTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TableNameLabel)
                            .addComponent(TableNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 481, Short.MAX_VALUE)
                        .addGroup(TableTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TableRemoveButton)
                            .addComponent(TableUpdateButton)
                            .addComponent(TableAddButton)))
                    .addComponent(jScrollPane6))
                .addContainerGap())
        );

        ManagementTabbedPane.addTab("Tables", TableTab);

        javax.swing.GroupLayout ManagementTabLayout = new javax.swing.GroupLayout(ManagementTab);
        ManagementTab.setLayout(ManagementTabLayout);
        ManagementTabLayout.setHorizontalGroup(
            ManagementTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 601, Short.MAX_VALUE)
            .addGroup(ManagementTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(ManagementTabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, 601, Short.MAX_VALUE))
        );
        ManagementTabLayout.setVerticalGroup(
            ManagementTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 700, Short.MAX_VALUE)
            .addGroup(ManagementTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(ManagementTabbedPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        BarMainTabbedPane.addTab("Management", ManagementTab);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 692, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(BarMainTabbedPane, javax.swing.GroupLayout.Alignment.TRAILING))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 710, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(BarMainTabbedPane)
                    .addContainerGap()))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ProductNameTextFİeldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProductNameTextFİeldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ProductNameTextFİeldActionPerformed

    private void Table1ButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Table1ButtonMouseClicked
        TableContent tc = new TableContent();
        tc.setVisible(true);
    }//GEN-LAST:event_Table1ButtonMouseClicked

    private void ProductPriceTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProductPriceTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ProductPriceTextFieldActionPerformed

    private void ProductAddButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ProductAddButtonMouseClicked
        ProductCreate pc = new ProductCreate();
        pc.setVisible(true);
    }//GEN-LAST:event_ProductAddButtonMouseClicked

    private void TableNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TableNameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TableNameTextFieldActionPerformed

    private void WaiterNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WaiterNameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_WaiterNameTextFieldActionPerformed

    private void WaiterAddButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_WaiterAddButtonMouseClicked
        WaiterCreate wc = new WaiterCreate();
        wc.setVisible(true);
    }//GEN-LAST:event_WaiterAddButtonMouseClicked

    private void WaiterSSNTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WaiterSSNTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_WaiterSSNTextFieldActionPerformed

    private void WaiterPhoneNumberTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WaiterPhoneNumberTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_WaiterPhoneNumberTextFieldActionPerformed

    private void CategoryCreateButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CategoryCreateButtonMouseClicked
       CategoryCreate cc = new CategoryCreate();
       cc.setVisible(true);
    }//GEN-LAST:event_CategoryCreateButtonMouseClicked

    private void ProductAddButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProductAddButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ProductAddButtonActionPerformed

    private void CategoryRemoveButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CategoryRemoveButtonMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_CategoryRemoveButtonMouseClicked

    private void CategoryUpdateButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CategoryUpdateButtonMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_CategoryUpdateButtonMouseClicked

    private void ProductRemoveButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ProductRemoveButtonMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_ProductRemoveButtonMouseClicked

    private void ProductUpdateButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ProductUpdateButtonMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_ProductUpdateButtonMouseClicked

    private void WaiterRemoveButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_WaiterRemoveButtonMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_WaiterRemoveButtonMouseClicked

    private void WaiterUpdateButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_WaiterUpdateButtonMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_WaiterUpdateButtonMouseClicked

    private void TableAddButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableAddButtonMouseClicked
       TableCreate tc = new TableCreate();
       tc.setVisible(true);
    }//GEN-LAST:event_TableAddButtonMouseClicked

    private void TableUpdateButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableUpdateButtonMouseClicked
        //TODO add your handling code here:
    }//GEN-LAST:event_TableUpdateButtonMouseClicked

    private void CategoryTypeComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CategoryTypeComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CategoryTypeComboBoxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws UnsupportedLookAndFeelException {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
       javax.swing.plaf.basic.BasicLookAndFeel darcula = new DarculaLaf();
        javax.swing.UIManager.setLookAndFeel(darcula);
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Bar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane BarMainTabbedPane;
    private javax.swing.JButton CategoryCreateButton;
    private javax.swing.JLabel CategoryDescriptionLabel;
    private javax.swing.JTextArea CategoryDescriptionTextArea;
    private javax.swing.JLabel CategoryIDLabel;
    private javax.swing.JLabel CategoryIDLabel1;
    private javax.swing.JTextField CategoryIDTextField;
    private javax.swing.JList<String> CategoryList;
    private javax.swing.JLabel CategoryNameLabel;
    private javax.swing.JTextField CategoryNameTextField;
    private javax.swing.JButton CategoryRemoveButton;
    private javax.swing.JPanel CategoryTab;
    private javax.swing.JComboBox<String> CategoryTypeComboBox;
    private javax.swing.JButton CategoryUpdateButton;
    private javax.swing.JScrollPane JScrollPane;
    private javax.swing.JPanel MainTableTab;
    private javax.swing.JPanel ManagementTab;
    private javax.swing.JTabbedPane ManagementTabbedPane;
    private javax.swing.JButton ProductAddButton;
    private javax.swing.JLabel ProductAlcoholVolumeLabel;
    private javax.swing.JTextField ProductAlcoholVolumeTextField;
    private javax.swing.JLabel ProductBrandLabel;
    private javax.swing.JTextField ProductBrandTextField;
    private javax.swing.JComboBox<String> ProductCategoryComboBox;
    private javax.swing.JLabel ProductCategoryLabel;
    private javax.swing.JLabel ProductDescriptionLabel;
    private javax.swing.JTextArea ProductDescriptionTextArea;
    private javax.swing.JLabel ProductIDLabel;
    private javax.swing.JTextField ProductIDTextField;
    private javax.swing.JList<String> ProductList;
    private javax.swing.JLabel ProductNameLabel;
    private javax.swing.JTextField ProductNameTextFİeld;
    private javax.swing.JLabel ProductPriceLabel;
    private javax.swing.JTextField ProductPriceTextField;
    private javax.swing.JButton ProductRemoveButton;
    private javax.swing.JPanel ProductTab;
    private javax.swing.JButton ProductUpdateButton;
    private javax.swing.JButton Table1Button;
    private javax.swing.JButton TableAddButton;
    private javax.swing.JLabel TableIDLabel;
    private javax.swing.JTextField TableIDTextField;
    private javax.swing.JList<String> TableList;
    private javax.swing.JLabel TableNameLabel;
    private javax.swing.JTextField TableNameTextField;
    private javax.swing.JButton TableRemoveButton;
    private javax.swing.JLabel TableShortCodeLabel;
    private javax.swing.JTextField TableShortCodeTextField;
    private javax.swing.JPanel TableTab;
    private javax.swing.JButton TableUpdateButton;
    private javax.swing.JButton WaiterAddButton;
    private javax.swing.JLabel WaiterIDLabel;
    private javax.swing.JTextField WaiterIDTextField;
    private javax.swing.JList<String> WaiterList;
    private javax.swing.JLabel WaiterNameLabel;
    private javax.swing.JTextField WaiterNameTextField;
    private javax.swing.JLabel WaiterPhoneNumberLabel;
    private javax.swing.JTextField WaiterPhoneNumberTextField;
    private javax.swing.JButton WaiterRemoveButton;
    private javax.swing.JLabel WaiterSSNLabel;
    private javax.swing.JTextField WaiterSSNTextField;
    private javax.swing.JPanel WaiterTab;
    private javax.swing.JButton WaiterUpdateButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    // End of variables declaration//GEN-END:variables
}
