/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.eyse360.gui;

import com.eyse360.controllers.mysql.*;
import com.eyse360.models.Bar;
import com.eyse360.models.BarUser;
import com.eyse360.models.Beverage;
import com.eyse360.models.Category;
import com.eyse360.models.Check;
import com.eyse360.models.Product;
import com.eyse360.models.Table;
import com.eyse360.models.Waiter;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;

import javax.swing.*;
import java.util.List;
import java.util.Map;
import javax.swing.Box.Filler;

/**
 *
 * @author Erel
 */
public class BarFrame extends javax.swing.JFrame {

    /**
     * Creates new form Bar
     */
    public static BarDAO barDao;
    public static CategoryDAO categoryDao;
    public static ProductDAO productDao;
    public static BarUserDAO barUserDao;
    public static TableDAO tableDao;
    
    public static Bar currentBar;
    public static BarUser currentUser;
    public static Category[] categoryArray;
    
    public static DefaultListModel<Category> categoryModel;
    public static DefaultListModel<Product> productModel;
    public static DefaultListModel<Table> tableModel;
    public static DefaultListModel<Waiter> waiterModel;
    
    public static DefaultComboBoxModel<Category> categoryComboBoxModel;
    
    public BarFrame(BarUser user) {
        currentBar = user.getBar();
        currentUser = user;
        
        barDao = new BarDAO();
        categoryDao = new CategoryDAO();
        productDao = new ProductDAO();
        barUserDao = new BarUserDAO();
        tableDao = new TableDAO();
        currentBar = barDao.get(currentBar);
        
        initComponents();
        
        if (user.getRole().equals("waiter")) {
            BarMainTabbedPane.remove(1);
        } else {
        
            categoryModel = new DefaultListModel<>();
            CategoryList.setModel(categoryModel);

            productModel = new DefaultListModel<>();
            ProductList.setModel(productModel);

            tableModel = new DefaultListModel<>();
            TableList.setModel(tableModel);

            waiterModel = new DefaultListModel<>();
            WaiterList.setModel(waiterModel);

            categoryComboBoxModel = new DefaultComboBoxModel<>();
            ProductCategoryComboBox.setModel(categoryComboBoxModel);
        }
    }
    
    private void TableButtonMouseClicked(java.awt.event.MouseEvent evt, Table table) {
        TableContentFrame tc = new TableContentFrame(table, currentUser);
        tc.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BarMainTabbedPane = new javax.swing.JTabbedPane();
        MainTableTab = new javax.swing.JPanel();
        ManagementTab = new javax.swing.JPanel();
        ManagementTabbedPane = new javax.swing.JTabbedPane();
        CategoryTab = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        CategoryList = new javax.swing.JList<>();
        CategoryIDLabel = new javax.swing.JLabel();
        CategoryNameLabel = new javax.swing.JLabel();
        CategoryDescriptionLabel = new javax.swing.JLabel();
        CategoryIDTextField = new javax.swing.JTextField();
        CategoryNameTextField = new javax.swing.JTextField();
        JScrollPane = new javax.swing.JScrollPane();
        CategoryDescriptionTextArea = new javax.swing.JTextArea();
        CategoryIDLabel1 = new javax.swing.JLabel();
        CategoryCreateButton = new javax.swing.JButton();
        CategoryRemoveButton = new javax.swing.JButton();
        CategoryUpdateButton = new javax.swing.JButton();
        CategoryTypeComboBox = new javax.swing.JComboBox<>();
        ProductTab = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        ProductList = new javax.swing.JList<>();
        ProductIDLabel = new javax.swing.JLabel();
        ProductNameLabel = new javax.swing.JLabel();
        ProductDescriptionLabel = new javax.swing.JLabel();
        ProductIDTextField = new javax.swing.JTextField();
        ProductNameTextField = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        ProductDescriptionTextArea = new javax.swing.JTextArea();
        ProductPriceLabel = new javax.swing.JLabel();
        ProductPriceTextField = new javax.swing.JTextField();
        ProductCategoryLabel = new javax.swing.JLabel();
        ProductCategoryComboBox = new javax.swing.JComboBox<>();
        ProductAddButton = new javax.swing.JButton();
        ProductRemoveButton = new javax.swing.JButton();
        ProductUpdateButton = new javax.swing.JButton();
        ProductBrandLabel = new javax.swing.JLabel();
        ProductBrandTextField = new javax.swing.JTextField();
        ProductAlcoholVolumeLabel = new javax.swing.JLabel();
        ProductAlcoholVolumeTextField = new javax.swing.JTextField();
        WaiterTab = new javax.swing.JPanel();
        jScrollPane7 = new javax.swing.JScrollPane();
        WaiterList = new javax.swing.JList<>();
        WaiterIDLabel = new javax.swing.JLabel();
        WaiterNameLabel = new javax.swing.JLabel();
        WaiterIDTextField = new javax.swing.JTextField();
        WaiterNameTextField = new javax.swing.JTextField();
        WaiterAddButton = new javax.swing.JButton();
        WaiterRemoveButton = new javax.swing.JButton();
        WaiterUpdateButton = new javax.swing.JButton();
        WaiterSSNLabel = new javax.swing.JLabel();
        WaiterSSNTextField = new javax.swing.JTextField();
        WaiterPhoneNumberLabel = new javax.swing.JLabel();
        WaiterPhoneNumberTextField = new javax.swing.JTextField();
        WaiterUserNameLabel = new javax.swing.JLabel();
        WaiterUserNameTextField = new javax.swing.JTextField();
        WaiterPasswordLabel = new javax.swing.JLabel();
        WaiterPasswordTextField = new javax.swing.JPasswordField();
        WaiterShowPasswordCheckbox = new javax.swing.JCheckBox();
        TableTab = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        TableList = new javax.swing.JList<>();
        TableAddButton = new javax.swing.JButton();
        TableRemoveButton = new javax.swing.JButton();
        TableShortCodeLabel = new javax.swing.JLabel();
        TableShortCodeTextField = new javax.swing.JTextField();
        TableNameLabel = new javax.swing.JLabel();
        TableNameTextField = new javax.swing.JTextField();
        TableIDLabel = new javax.swing.JLabel();
        TableIDTextField = new javax.swing.JTextField();
        TableUpdateButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(700, 700));
        setResizable(false);

        BarMainTabbedPane.setTabPlacement(javax.swing.JTabbedPane.LEFT);
        BarMainTabbedPane.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                BarMainTabbedPaneStateChanged(evt);
            }
        });

        MainTableTab.setLayout(new java.awt.GridLayout(3, 0));
        BarMainTabbedPane.addTab("Table", MainTableTab);

        ManagementTabbedPane.setMinimumSize(new java.awt.Dimension(700, 700));
        ManagementTabbedPane.setPreferredSize(new java.awt.Dimension(700, 700));
        ManagementTabbedPane.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                ManagementTabbedPaneStateChanged(evt);
            }
        });

        CategoryList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        CategoryList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CategoryListMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(CategoryList);

        CategoryIDLabel.setText("ID");
        CategoryIDLabel.setToolTipText("");

        CategoryNameLabel.setText("Name");

        CategoryDescriptionLabel.setText("Description");

        CategoryIDTextField.setEditable(false);

        CategoryDescriptionTextArea.setColumns(20);
        CategoryDescriptionTextArea.setRows(5);
        JScrollPane.setViewportView(CategoryDescriptionTextArea);

        CategoryIDLabel1.setText("Type");
        CategoryIDLabel1.setToolTipText("");

        CategoryCreateButton.setText("Add");
        CategoryCreateButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CategoryCreateButtonMouseClicked(evt);
            }
        });

        CategoryRemoveButton.setText("Remove");
        CategoryRemoveButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CategoryRemoveButtonMouseClicked(evt);
            }
        });

        CategoryUpdateButton.setText("Update");
        CategoryUpdateButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CategoryUpdateButtonMouseClicked(evt);
            }
        });

        CategoryTypeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "food", "beverage" }));
        CategoryTypeComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CategoryTypeComboBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout CategoryTabLayout = new javax.swing.GroupLayout(CategoryTab);
        CategoryTab.setLayout(CategoryTabLayout);
        CategoryTabLayout.setHorizontalGroup(
            CategoryTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CategoryTabLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(CategoryTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CategoryTabLayout.createSequentialGroup()
                        .addGroup(CategoryTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(CategoryTabLayout.createSequentialGroup()
                                .addComponent(CategoryNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(CategoryNameTextField))
                            .addGroup(CategoryTabLayout.createSequentialGroup()
                                .addComponent(CategoryDescriptionLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(JScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE)))
                        .addGap(6, 6, 6))
                    .addGroup(CategoryTabLayout.createSequentialGroup()
                        .addComponent(CategoryIDLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(CategoryIDTextField))
                    .addGroup(CategoryTabLayout.createSequentialGroup()
                        .addComponent(CategoryRemoveButton)
                        .addGap(66, 66, 66)
                        .addComponent(CategoryUpdateButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(CategoryCreateButton)
                        .addContainerGap())
                    .addGroup(CategoryTabLayout.createSequentialGroup()
                        .addComponent(CategoryIDLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(CategoryTypeComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        CategoryTabLayout.setVerticalGroup(
            CategoryTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CategoryTabLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1))
            .addGroup(CategoryTabLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(CategoryTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CategoryIDLabel)
                    .addComponent(CategoryIDTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(CategoryTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CategoryNameLabel)
                    .addComponent(CategoryNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(70, 70, 70)
                .addGroup(CategoryTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CategoryIDLabel1)
                    .addComponent(CategoryTypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(CategoryTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CategoryTabLayout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(JScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(CategoryTabLayout.createSequentialGroup()
                        .addGap(149, 149, 149)
                        .addComponent(CategoryDescriptionLabel)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 180, Short.MAX_VALUE)
                .addGroup(CategoryTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CategoryUpdateButton)
                    .addComponent(CategoryRemoveButton)
                    .addComponent(CategoryCreateButton))
                .addContainerGap())
        );

        ManagementTabbedPane.addTab("Categories", CategoryTab);

        ProductList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        ProductList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ProductListMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(ProductList);

        ProductIDLabel.setText("ID");
        ProductIDLabel.setToolTipText("");

        ProductNameLabel.setText("Name");

        ProductDescriptionLabel.setText("Description");

        ProductIDTextField.setEnabled(false);

        ProductDescriptionTextArea.setColumns(20);
        ProductDescriptionTextArea.setRows(5);
        jScrollPane4.setViewportView(ProductDescriptionTextArea);

        ProductPriceLabel.setText("Price");
        ProductPriceLabel.setToolTipText("");

        ProductPriceTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProductPriceTextFieldActionPerformed(evt);
            }
        });

        ProductCategoryLabel.setText("Category");

        ProductCategoryComboBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                ProductCategoryComboBoxItemStateChanged(evt);
            }
        });
        ProductCategoryComboBox.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                ProductCategoryComboBoxPropertyChange(evt);
            }
        });

        ProductAddButton.setText("Add");
        ProductAddButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ProductAddButtonMouseClicked(evt);
            }
        });
        ProductAddButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProductAddButtonActionPerformed(evt);
            }
        });

        ProductRemoveButton.setText("Remove");
        ProductRemoveButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ProductRemoveButtonMouseClicked(evt);
            }
        });

        ProductUpdateButton.setText("Update");
        ProductUpdateButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ProductUpdateButtonMouseClicked(evt);
            }
        });

        ProductBrandLabel.setText("Brand");

        ProductAlcoholVolumeLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ProductAlcoholVolumeLabel.setText("Alcohol Volume");
        ProductAlcoholVolumeLabel.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        javax.swing.GroupLayout ProductTabLayout = new javax.swing.GroupLayout(ProductTab);
        ProductTab.setLayout(ProductTabLayout);
        ProductTabLayout.setHorizontalGroup(
            ProductTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ProductTabLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ProductTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ProductTabLayout.createSequentialGroup()
                        .addGroup(ProductTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ProductCategoryLabel)
                            .addComponent(ProductNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ProductIDLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 33, Short.MAX_VALUE))
                    .addGroup(ProductTabLayout.createSequentialGroup()
                        .addGroup(ProductTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ProductPriceLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ProductBrandLabel)
                            .addComponent(ProductAlcoholVolumeLabel)
                            .addComponent(ProductRemoveButton)
                            .addComponent(ProductDescriptionLabel))
                        .addGap(33, 43, Short.MAX_VALUE)))
                .addGroup(ProductTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ProductTabLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(ProductUpdateButton)
                        .addGap(92, 92, 92)
                        .addComponent(ProductAddButton))
                    .addGroup(ProductTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(ProductBrandTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
                        .addComponent(ProductAlcoholVolumeTextField)
                        .addComponent(ProductNameTextField)
                        .addComponent(ProductCategoryComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane4)
                        .addComponent(ProductPriceTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
                        .addComponent(ProductIDTextField)))
                .addGap(6, 6, 6))
        );
        ProductTabLayout.setVerticalGroup(
            ProductTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ProductTabLayout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addGroup(ProductTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3)
                    .addGroup(ProductTabLayout.createSequentialGroup()
                        .addGroup(ProductTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ProductIDLabel)
                            .addComponent(ProductIDTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(ProductTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ProductNameLabel)
                            .addComponent(ProductNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addGroup(ProductTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ProductCategoryComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ProductCategoryLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                        .addGroup(ProductTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(ProductTabLayout.createSequentialGroup()
                                .addGap(64, 64, 64)
                                .addComponent(ProductDescriptionLabel)))
                        .addGap(18, 18, 18)
                        .addGroup(ProductTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ProductPriceLabel)
                            .addComponent(ProductPriceTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(ProductTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ProductBrandLabel)
                            .addComponent(ProductBrandTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(ProductTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ProductAlcoholVolumeLabel)
                            .addComponent(ProductAlcoholVolumeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(237, 237, 237)
                        .addGroup(ProductTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ProductAddButton)
                            .addComponent(ProductRemoveButton)
                            .addComponent(ProductUpdateButton))))
                .addContainerGap())
        );

        ProductBrandLabel.setVisible(false);
        ProductBrandTextField.setVisible(false);
        ProductAlcoholVolumeLabel.setVisible(false);
        ProductAlcoholVolumeTextField.setVisible(false);

        ManagementTabbedPane.addTab("Products", ProductTab);

        WaiterList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        WaiterList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                WaiterListMouseClicked(evt);
            }
        });
        jScrollPane7.setViewportView(WaiterList);

        WaiterIDLabel.setText("ID");
        WaiterIDLabel.setToolTipText("");

        WaiterNameLabel.setText("Name");

        WaiterIDTextField.setEnabled(false);

        WaiterNameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WaiterNameTextFieldActionPerformed(evt);
            }
        });

        WaiterAddButton.setText("Add");
        WaiterAddButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                WaiterAddButtonMouseClicked(evt);
            }
        });

        WaiterRemoveButton.setText("Remove");
        WaiterRemoveButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                WaiterRemoveButtonMouseClicked(evt);
            }
        });

        WaiterUpdateButton.setText("Update");
        WaiterUpdateButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                WaiterUpdateButtonMouseClicked(evt);
            }
        });

        WaiterSSNLabel.setText("SSN");

        WaiterSSNTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WaiterSSNTextFieldActionPerformed(evt);
            }
        });

        WaiterPhoneNumberLabel.setText("Phone Number");

        WaiterPhoneNumberTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WaiterPhoneNumberTextFieldActionPerformed(evt);
            }
        });

        WaiterUserNameLabel.setText("Username");

        WaiterPasswordLabel.setText("Password");

        WaiterShowPasswordCheckbox.setText("Show Password");
        WaiterShowPasswordCheckbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WaiterShowPasswordCheckboxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout WaiterTabLayout = new javax.swing.GroupLayout(WaiterTab);
        WaiterTab.setLayout(WaiterTabLayout);
        WaiterTabLayout.setHorizontalGroup(
            WaiterTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(WaiterTabLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(WaiterTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(WaiterTabLayout.createSequentialGroup()
                        .addComponent(WaiterRemoveButton)
                        .addGap(84, 84, 84)
                        .addComponent(WaiterUpdateButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 76, Short.MAX_VALUE)
                        .addComponent(WaiterAddButton))
                    .addGroup(WaiterTabLayout.createSequentialGroup()
                        .addGroup(WaiterTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(WaiterNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(WaiterSSNLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(WaiterPhoneNumberLabel))
                        .addGap(14, 14, 14)
                        .addGroup(WaiterTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(WaiterSSNTextField, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(WaiterNameTextField)
                            .addComponent(WaiterPhoneNumberTextField)))
                    .addGroup(WaiterTabLayout.createSequentialGroup()
                        .addGroup(WaiterTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(WaiterIDLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(WaiterUserNameLabel)
                            .addComponent(WaiterPasswordLabel))
                        .addGap(39, 39, 39)
                        .addGroup(WaiterTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(WaiterIDTextField)
                            .addComponent(WaiterUserNameTextField)
                            .addComponent(WaiterPasswordTextField)
                            .addGroup(WaiterTabLayout.createSequentialGroup()
                                .addComponent(WaiterShowPasswordCheckbox)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        WaiterTabLayout.setVerticalGroup(
            WaiterTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(WaiterTabLayout.createSequentialGroup()
                .addGroup(WaiterTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(WaiterTabLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(WaiterTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(WaiterIDLabel)
                            .addComponent(WaiterIDTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(WaiterTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(WaiterUserNameLabel)
                            .addComponent(WaiterUserNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(WaiterTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(WaiterPasswordLabel)
                            .addComponent(WaiterPasswordTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15)
                        .addComponent(WaiterShowPasswordCheckbox)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(WaiterTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(WaiterNameLabel)
                            .addComponent(WaiterNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(WaiterTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(WaiterSSNLabel)
                            .addComponent(WaiterSSNTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(WaiterTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(WaiterPhoneNumberLabel)
                            .addComponent(WaiterPhoneNumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(WaiterTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(WaiterRemoveButton)
                            .addComponent(WaiterUpdateButton)
                            .addComponent(WaiterAddButton)))
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 668, Short.MAX_VALUE))
                .addContainerGap())
        );

        ManagementTabbedPane.addTab("Waiters", WaiterTab);

        TableList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        TableList.setToolTipText("");
        TableList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableListMouseClicked(evt);
            }
        });
        jScrollPane6.setViewportView(TableList);

        TableAddButton.setText("Add");
        TableAddButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableAddButtonMouseClicked(evt);
            }
        });

        TableRemoveButton.setText("Remove");
        TableRemoveButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableRemoveButtonMouseClicked(evt);
            }
        });

        TableShortCodeLabel.setText("Short Code");

        TableNameLabel.setText("Name");

        TableNameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TableNameTextFieldActionPerformed(evt);
            }
        });

        TableIDLabel.setText("ID");

        TableIDTextField.setEditable(false);

        TableUpdateButton.setText("Update");
        TableUpdateButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableUpdateButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout TableTabLayout = new javax.swing.GroupLayout(TableTab);
        TableTab.setLayout(TableTabLayout);
        TableTabLayout.setHorizontalGroup(
            TableTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TableTabLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(TableTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(TableTabLayout.createSequentialGroup()
                        .addComponent(TableRemoveButton)
                        .addGap(80, 80, 80)
                        .addComponent(TableUpdateButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 84, Short.MAX_VALUE)
                        .addComponent(TableAddButton))
                    .addGroup(TableTabLayout.createSequentialGroup()
                        .addComponent(TableNameLabel)
                        .addGap(90, 90, 90)
                        .addComponent(TableNameTextField))
                    .addGroup(TableTabLayout.createSequentialGroup()
                        .addComponent(TableShortCodeLabel)
                        .addGap(60, 60, 60)
                        .addComponent(TableShortCodeTextField))
                    .addGroup(TableTabLayout.createSequentialGroup()
                        .addComponent(TableIDLabel)
                        .addGap(112, 112, 112)
                        .addComponent(TableIDTextField)))
                .addContainerGap())
        );
        TableTabLayout.setVerticalGroup(
            TableTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TableTabLayout.createSequentialGroup()
                .addGroup(TableTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(TableTabLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(TableTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TableIDLabel)
                            .addComponent(TableIDTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addGroup(TableTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TableShortCodeLabel)
                            .addComponent(TableShortCodeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(TableTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TableNameLabel)
                            .addComponent(TableNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 481, Short.MAX_VALUE)
                        .addGroup(TableTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TableRemoveButton)
                            .addComponent(TableUpdateButton)
                            .addComponent(TableAddButton)))
                    .addComponent(jScrollPane6))
                .addContainerGap())
        );

        ManagementTabbedPane.addTab("Tables", TableTab);

        javax.swing.GroupLayout ManagementTabLayout = new javax.swing.GroupLayout(ManagementTab);
        ManagementTab.setLayout(ManagementTabLayout);
        ManagementTabLayout.setHorizontalGroup(
            ManagementTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 601, Short.MAX_VALUE)
            .addGroup(ManagementTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(ManagementTabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, 601, Short.MAX_VALUE))
        );
        ManagementTabLayout.setVerticalGroup(
            ManagementTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 700, Short.MAX_VALUE)
            .addGroup(ManagementTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(ManagementTabbedPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        BarMainTabbedPane.addTab("Management", ManagementTab);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 692, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(BarMainTabbedPane, javax.swing.GroupLayout.Alignment.TRAILING))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 710, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(BarMainTabbedPane)
                    .addContainerGap()))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ProductPriceTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProductPriceTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ProductPriceTextFieldActionPerformed

    private void ProductAddButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ProductAddButtonMouseClicked
        ProductCreateFrame pc = new ProductCreateFrame();
        pc.setVisible(true);
    }//GEN-LAST:event_ProductAddButtonMouseClicked

    private void TableNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TableNameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TableNameTextFieldActionPerformed

    private void WaiterNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WaiterNameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_WaiterNameTextFieldActionPerformed

    private void WaiterAddButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_WaiterAddButtonMouseClicked
        WaiterCreateFrame wc = new WaiterCreateFrame();
        wc.setVisible(true);
    }//GEN-LAST:event_WaiterAddButtonMouseClicked

    private void WaiterSSNTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WaiterSSNTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_WaiterSSNTextFieldActionPerformed

    private void WaiterPhoneNumberTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WaiterPhoneNumberTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_WaiterPhoneNumberTextFieldActionPerformed

    private void CategoryCreateButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CategoryCreateButtonMouseClicked
       CategoryCreateFrame cc = new CategoryCreateFrame();
       cc.setVisible(true);
    }//GEN-LAST:event_CategoryCreateButtonMouseClicked

    private void ProductAddButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProductAddButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ProductAddButtonActionPerformed

    private void CategoryRemoveButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CategoryRemoveButtonMouseClicked
        Category category = CategoryList.getSelectedValue();
        int index = CategoryList.getSelectedIndex();
        categoryDao.delete(category);
        categoryModel.remove(index);
        
        resetCategoryForm();
    }//GEN-LAST:event_CategoryRemoveButtonMouseClicked

    private void CategoryUpdateButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CategoryUpdateButtonMouseClicked
        Category category = CategoryList.getSelectedValue();
        category.setName(CategoryNameTextField.getText());
        category.setDescription(CategoryDescriptionTextArea.getText());
        category.setType((String) CategoryTypeComboBox.getSelectedItem());
        categoryDao.update(category);
        
        CategoryList.updateUI();
    }//GEN-LAST:event_CategoryUpdateButtonMouseClicked

    private void ProductRemoveButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ProductRemoveButtonMouseClicked
        Product product = ProductList.getSelectedValue();
        int index = ProductList.getSelectedIndex();
        productDao.delete(product);
        productModel.remove(index);
        
        resetProductForm();
    }//GEN-LAST:event_ProductRemoveButtonMouseClicked

    private void ProductUpdateButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ProductUpdateButtonMouseClicked
        Product product = ProductList.getSelectedValue();
        product.setName(ProductNameTextField.getText());
        product.setDescription(ProductDescriptionTextArea.getText());
        product.setPrice(Double.parseDouble(ProductPriceTextField.getText()));
        product.setCategory((Category) ProductCategoryComboBox.getSelectedItem());
        
        if (product instanceof Beverage) {
            ((Beverage) product).setBrand(ProductBrandTextField.getText());
            ((Beverage) product).setAlcoholVolume(Double.parseDouble(ProductAlcoholVolumeTextField.getText()));
        }
        
        productDao.update(product);
        
        ProductList.updateUI();
    }//GEN-LAST:event_ProductUpdateButtonMouseClicked

    private void WaiterRemoveButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_WaiterRemoveButtonMouseClicked
        Waiter waiter = WaiterList.getSelectedValue();
        int index = WaiterList.getSelectedIndex();
        barUserDao.delete(waiter);
        waiterModel.remove(index);
        
        resetWaiterForm();
    }//GEN-LAST:event_WaiterRemoveButtonMouseClicked

    private void WaiterUpdateButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_WaiterUpdateButtonMouseClicked
        Waiter waiter = WaiterList.getSelectedValue();
        waiter.setUserName(WaiterUserNameTextField.getText());
        waiter.setPassword(WaiterPasswordTextField.getText());
        waiter.setFullName(WaiterNameTextField.getText());
        waiter.setSSN(WaiterSSNTextField.getText());
        waiter.setPhoneNumber(WaiterPhoneNumberTextField.getText());
        
        barUserDao.update(waiter);
        
        WaiterList.updateUI();
    }//GEN-LAST:event_WaiterUpdateButtonMouseClicked

    private void TableAddButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableAddButtonMouseClicked
       TableCreateFrame tc = new TableCreateFrame();
       tc.setVisible(true);
    }//GEN-LAST:event_TableAddButtonMouseClicked

    private void TableUpdateButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableUpdateButtonMouseClicked
        Table table = TableList.getSelectedValue();
        table.setName(TableNameTextField.getText());
        table.setShortCode(TableShortCodeTextField.getText());
        
        tableDao.update(table);
        TableList.updateUI();
    }//GEN-LAST:event_TableUpdateButtonMouseClicked

    private void CategoryTypeComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CategoryTypeComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CategoryTypeComboBoxActionPerformed

    private void BarMainTabbedPaneStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_BarMainTabbedPaneStateChanged
        if (BarMainTabbedPane.getSelectedIndex() == 0) {
            MainTableTab.removeAll();
            List<Table> tableList = tableDao.getAllByBar(currentBar);
            if (tableList != null) {
                for (Table table : tableList) {
                    Filler topToBottomFiller = new Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));
                    Filler bottomToTopFiller = new Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));
                    JPanel tablePanel = new JPanel();
                    tablePanel.setBorder(BorderFactory.createLineBorder(Color.decode("#214283")));
                    tablePanel.setLayout(new BoxLayout(tablePanel, BoxLayout.Y_AXIS));
                    tablePanel.add(topToBottomFiller);

                    JLabel tableButton = new JLabel(table.getName());
                    tableButton.setFont(new Font("Dialog", 1, 18));
                    tableButton.setHorizontalAlignment(SwingConstants.CENTER);
                    tableButton.setMaximumSize(new Dimension(350, 50));
                    tableButton.setPreferredSize(new java.awt.Dimension(150, 54));
                    tableButton.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseClicked(java.awt.event.MouseEvent evt) {
                            TableButtonMouseClicked(evt, table);
                        }
                    });
                    tablePanel.add(tableButton);

                    Check check = tableDao.getOpenCheckDetailByTable(table);
                    if (check != null) {
                        if (check.isIsOpen()) {
                            check.setProducts(tableDao.getTableProducts(check));

                            double sum = 0;
                            JLabel totalPriceLabel = new JLabel(String.valueOf(sum));
                            totalPriceLabel.setHorizontalAlignment(SwingConstants.CENTER);
                            totalPriceLabel.setMaximumSize(new Dimension(350, 50));
                            if (check.getProducts() != null) {
                                for (Map.Entry<Product, Integer> entry : check.getProducts().entrySet()) {
                                    sum += entry.getKey().getPrice() * entry.getValue();
                                }
                                System.out.println(sum);
                                totalPriceLabel.setText(String.valueOf(sum));
                            }
                            tablePanel.add(totalPriceLabel);
                            tablePanel.setBackground(Color.decode("#629755"));
                        }
                    }
                    tablePanel.add(bottomToTopFiller);
                    MainTableTab.add(tablePanel);
                }
            }
        } else if (BarMainTabbedPane.getSelectedIndex() == 1) {
            categoryModel.removeAllElements();
            List<Category> categoryList = categoryDao.getAllByBar(currentBar);
            if (categoryList != null) {
                for (Category category : categoryList)
                    categoryModel.addElement(category);
            }
        }
    }//GEN-LAST:event_BarMainTabbedPaneStateChanged

    private void CategoryListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CategoryListMouseClicked
        Category selected = CategoryList.getSelectedValue();
        CategoryIDTextField.setText(String.valueOf(selected.getId()));
        CategoryNameTextField.setText(selected.getName());
        CategoryDescriptionTextArea.setText(selected.getDescription());
        CategoryTypeComboBox.setSelectedItem(selected.getType());
    }//GEN-LAST:event_CategoryListMouseClicked

    private void ManagementTabbedPaneStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_ManagementTabbedPaneStateChanged
        System.out.println(BarMainTabbedPane.getSelectedIndex());
        if (BarMainTabbedPane.getSelectedIndex() == 1) {
            int currentIndex = ManagementTabbedPane.getSelectedIndex();
            if (currentIndex == 0) {
                categoryModel.removeAllElements();
                List<Category> categoryList = categoryDao.getAllByBar(currentBar);
                if (categoryList != null) {
                    for (Category category : categoryList)
                        categoryModel.addElement(category);
                }
            } else if (currentIndex == 1) {
                resetProductForm();
                productModel.removeAllElements();
                List<Product> productList = productDao.getAllByBar(currentBar);
                if (productList != null) {
                    for (Product product : productList)
                        productModel.addElement(product);
                }
            } else if (currentIndex == 2) {
                waiterModel.removeAllElements();
                List<Waiter> waiterList = barUserDao.getAllWaitersByBar(currentBar);
                if (waiterList != null) {
                    for (Waiter waiter : waiterList)
                        waiterModel.addElement(waiter);
                }
            } else if (currentIndex == 3) {
                tableModel.removeAllElements();
                List<Table> tableList = tableDao.getAllByBar(currentBar);
                if (tableList != null) {
                    for (Table table : tableList)
                        tableModel.addElement(table);
                }
            }
        }
    }//GEN-LAST:event_ManagementTabbedPaneStateChanged

    private void ProductListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ProductListMouseClicked
        // TODO add your handling code here:
        Product selected = ProductList.getSelectedValue();
        ProductIDTextField.setText(String.valueOf(selected.getId()));
        ProductNameTextField.setText(selected.getName());
        ProductPriceTextField.setText(String.valueOf(selected.getPrice()));
        ProductDescriptionTextArea.setText(selected.getDescription());
        
        List<Category> categories = categoryDao.getAllByBar(currentBar);
        
        categoryComboBoxModel.removeAllElements();
        for (Category cat : categories) {
            categoryComboBoxModel.addElement(cat);
        }
        
        ProductCategoryComboBox.setSelectedItem(selected.getCategory());
        
        if (selected instanceof Beverage) {
            ProductBrandLabel.setVisible(true);
            ProductBrandTextField.setVisible(true);
            ProductAlcoholVolumeLabel.setVisible(true);
            ProductAlcoholVolumeTextField.setVisible(true);
            ProductBrandTextField.setText(((Beverage) selected).getBrand());
            ProductAlcoholVolumeTextField.setText(String.valueOf(((Beverage) selected).getAlcoholVolume()));
        } else {
            ProductBrandLabel.setVisible(false);
            ProductBrandTextField.setVisible(false);
            ProductAlcoholVolumeLabel.setVisible(false);
            ProductAlcoholVolumeTextField.setVisible(false);
        }        
    }//GEN-LAST:event_ProductListMouseClicked

    private void ProductCategoryComboBoxPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_ProductCategoryComboBoxPropertyChange
        if (BarMainTabbedPane.getSelectedIndex() == 1) {
            Category category = (Category) ProductCategoryComboBox.getSelectedItem();
            if (category.getType().equals("beverage")) {
                ProductBrandLabel.setVisible(true);
                ProductBrandTextField.setVisible(true);
                ProductAlcoholVolumeLabel.setVisible(true);
                ProductAlcoholVolumeTextField.setVisible(true);
            } else if (category.getType().equals("food")) {
                ProductBrandLabel.setVisible(false);
                ProductBrandTextField.setVisible(false);
                ProductAlcoholVolumeLabel.setVisible(false);
                ProductAlcoholVolumeTextField.setVisible(false);
            }
        }
    }//GEN-LAST:event_ProductCategoryComboBoxPropertyChange

    private void ProductCategoryComboBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_ProductCategoryComboBox�temStateChanged
        
    }//GEN-LAST:event_ProductCategoryComboBox�temStateChanged

    private void WaiterListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_WaiterListMouseClicked
        Waiter selected = WaiterList.getSelectedValue();
        WaiterIDTextField.setText(String.valueOf(selected.getId()));
        WaiterUserNameTextField.setText(selected.getUserName());
        WaiterPasswordTextField.setText(selected.getPassword());
        WaiterNameTextField.setText(selected.getFullName());
        WaiterSSNTextField.setText(selected.getSSN());
        WaiterPhoneNumberTextField.setText(selected.getPhoneNumber());
    }//GEN-LAST:event_WaiterListMouseClicked

    private void WaiterShowPasswordCheckboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WaiterShowPasswordCheckboxActionPerformed
        if(WaiterShowPasswordCheckbox.isSelected()){
            WaiterPasswordTextField.setEchoChar((char)0);
        }
        else{
            WaiterPasswordTextField.setEchoChar('*');
        }
    }//GEN-LAST:event_WaiterShowPasswordCheckboxActionPerformed

    private void TableListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableListMouseClicked
        Table selected = TableList.getSelectedValue();
        TableIDTextField.setText(String.valueOf(selected.getId()));
        TableShortCodeTextField.setText(selected.getShortCode());
        TableNameTextField.setText(selected.getName());        
    }//GEN-LAST:event_TableListMouseClicked

    private void TableRemoveButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableRemoveButtonMouseClicked
        Table table = TableList.getSelectedValue();
        int index = TableList.getSelectedIndex();
        tableDao.delete(table);
        tableModel.remove(index);
        
        resetTableForm();
    }//GEN-LAST:event_TableRemoveButtonMouseClicked

    
    private void resetProductForm() {
        ProductIDTextField.setText("");
        ProductNameTextField.setText("");
        ProductPriceTextField.setText("");
        ProductDescriptionTextArea.setText("");
        
        ProductCategoryComboBox.removeAllItems();       
        
        ProductBrandLabel.setVisible(false);
        ProductBrandTextField.setVisible(false);
        ProductBrandTextField.setText("");
        ProductAlcoholVolumeLabel.setVisible(false);
        ProductAlcoholVolumeTextField.setVisible(false);
        ProductAlcoholVolumeTextField.setText("");
    }
    
    private void resetCategoryForm() {
        CategoryIDTextField.setText("");
        CategoryNameTextField.setText("");
        CategoryTypeComboBox.setSelectedIndex(0);
        CategoryDescriptionTextArea.setText("");
    }
    
    private void resetWaiterForm() {
        WaiterIDTextField.setText("");
        WaiterUserNameTextField.setText("");
        WaiterPasswordTextField.setText("");
        WaiterNameTextField.setText("");
        WaiterSSNTextField.setText("");
        WaiterPhoneNumberTextField.setText("");
    }
    
    private void resetTableForm() {
        TableIDTextField.setText("");
        TableShortCodeTextField.setText("");
        TableNameTextField.setText("");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JTabbedPane BarMainTabbedPane;
    private javax.swing.JButton CategoryCreateButton;
    private javax.swing.JLabel CategoryDescriptionLabel;
    private javax.swing.JTextArea CategoryDescriptionTextArea;
    private javax.swing.JLabel CategoryIDLabel;
    private javax.swing.JLabel CategoryIDLabel1;
    private javax.swing.JTextField CategoryIDTextField;
    public javax.swing.JList<Category> CategoryList;
    private javax.swing.JLabel CategoryNameLabel;
    private javax.swing.JTextField CategoryNameTextField;
    private javax.swing.JButton CategoryRemoveButton;
    private javax.swing.JPanel CategoryTab;
    private javax.swing.JComboBox<String> CategoryTypeComboBox;
    private javax.swing.JButton CategoryUpdateButton;
    private javax.swing.JScrollPane JScrollPane;
    private javax.swing.JPanel MainTableTab;
    private javax.swing.JPanel ManagementTab;
    private javax.swing.JTabbedPane ManagementTabbedPane;
    private javax.swing.JButton ProductAddButton;
    private javax.swing.JLabel ProductAlcoholVolumeLabel;
    private javax.swing.JTextField ProductAlcoholVolumeTextField;
    private javax.swing.JLabel ProductBrandLabel;
    private javax.swing.JTextField ProductBrandTextField;
    private javax.swing.JComboBox<Category> ProductCategoryComboBox;
    private javax.swing.JLabel ProductCategoryLabel;
    private javax.swing.JLabel ProductDescriptionLabel;
    private javax.swing.JTextArea ProductDescriptionTextArea;
    private javax.swing.JLabel ProductIDLabel;
    private javax.swing.JTextField ProductIDTextField;
    private javax.swing.JList<Product> ProductList;
    private javax.swing.JLabel ProductNameLabel;
    private javax.swing.JTextField ProductNameTextField;
    private javax.swing.JLabel ProductPriceLabel;
    private javax.swing.JTextField ProductPriceTextField;
    private javax.swing.JButton ProductRemoveButton;
    private javax.swing.JPanel ProductTab;
    private javax.swing.JButton ProductUpdateButton;
    private javax.swing.JButton TableAddButton;
    private javax.swing.JLabel TableIDLabel;
    private javax.swing.JTextField TableIDTextField;
    private javax.swing.JList<Table> TableList;
    private javax.swing.JLabel TableNameLabel;
    private javax.swing.JTextField TableNameTextField;
    private javax.swing.JButton TableRemoveButton;
    private javax.swing.JLabel TableShortCodeLabel;
    private javax.swing.JTextField TableShortCodeTextField;
    private javax.swing.JPanel TableTab;
    private javax.swing.JButton TableUpdateButton;
    private javax.swing.JButton WaiterAddButton;
    private javax.swing.JLabel WaiterIDLabel;
    private javax.swing.JTextField WaiterIDTextField;
    private javax.swing.JList<Waiter> WaiterList;
    private javax.swing.JLabel WaiterNameLabel;
    private javax.swing.JTextField WaiterNameTextField;
    private javax.swing.JLabel WaiterPasswordLabel;
    private javax.swing.JPasswordField WaiterPasswordTextField;
    private javax.swing.JLabel WaiterPhoneNumberLabel;
    private javax.swing.JTextField WaiterPhoneNumberTextField;
    private javax.swing.JButton WaiterRemoveButton;
    private javax.swing.JLabel WaiterSSNLabel;
    private javax.swing.JTextField WaiterSSNTextField;
    private javax.swing.JCheckBox WaiterShowPasswordCheckbox;
    private javax.swing.JPanel WaiterTab;
    private javax.swing.JButton WaiterUpdateButton;
    private javax.swing.JLabel WaiterUserNameLabel;
    private javax.swing.JTextField WaiterUserNameTextField;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    // End of variables declaration//GEN-END:variables
}
