/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.eyse360.gui;

import com.eyse360.controllers.mysql.CategoryDAO;
import com.eyse360.controllers.mysql.ProductDAO;
import com.eyse360.models.Beverage;
import com.eyse360.models.Category;
import com.eyse360.models.Food;
import com.eyse360.models.Product;
import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author Erel
 */
public class ProductCreateFrame extends javax.swing.JFrame {

    private static DefaultComboBoxModel<Category> categoryModel;
    private static ProductDAO productDao;
    private static CategoryDAO categoryDao;
    
    /**
     * Creates new form ProductCreate
     */
    public ProductCreateFrame() {
        productDao = new ProductDAO();
        categoryDao = new CategoryDAO();
        
        initComponents();
        
        categoryModel = new DefaultComboBoxModel<>();
        
        CategoryComboBox.setModel(categoryModel);
        
        categoryModel.addAll(categoryDao.getAllByBar(BarFrame.currentBar));
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CategoryLabel = new javax.swing.JLabel();
        NameLabel = new javax.swing.JLabel();
        PriceLabel = new javax.swing.JLabel();
        DescriptionLabel = new javax.swing.JLabel();
        AlcoholVolumeLabel = new javax.swing.JLabel();
        BrandLabel = new javax.swing.JLabel();
        CreateButton = new javax.swing.JButton();
        NameTextField = new javax.swing.JTextField();
        PriceTextField = new javax.swing.JTextField();
        AlcoholVolumeTextField = new javax.swing.JTextField();
        BrandTextField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        DescriptionTextArea = new javax.swing.JTextArea();
        CancelButton = new javax.swing.JButton();
        CategoryComboBox = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(700, 450));
        setResizable(false);

        CategoryLabel.setText("Category:");

        NameLabel.setText("Name:");

        PriceLabel.setText("Price:");

        DescriptionLabel.setText("Description:");

        AlcoholVolumeLabel.setText("Alcohol Volume:");

        BrandLabel.setText("Brand:");

        CreateButton.setText("Create");
        CreateButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CreateButtonMouseClicked(evt);
            }
        });

        DescriptionTextArea.setColumns(20);
        DescriptionTextArea.setRows(5);
        jScrollPane1.setViewportView(DescriptionTextArea);

        CancelButton.setText("Cancel");
        CancelButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CancelButtonMouseClicked(evt);
            }
        });

        CategoryComboBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                CategoryComboBoxItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(111, 111, 111)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BrandLabel)
                            .addComponent(AlcoholVolumeLabel)
                            .addComponent(DescriptionLabel)
                            .addComponent(PriceLabel)
                            .addComponent(NameLabel)
                            .addComponent(CategoryLabel))
                        .addGap(158, 158, 158)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addComponent(NameTextField)
                            .addComponent(PriceTextField)
                            .addComponent(CategoryComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(AlcoholVolumeTextField)
                            .addComponent(BrandTextField)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(CreateButton)
                        .addGap(89, 89, 89)
                        .addComponent(CancelButton)))
                .addGap(67, 67, 67))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CategoryLabel)
                    .addComponent(CategoryComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NameLabel)
                    .addComponent(NameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PriceLabel)
                    .addComponent(PriceTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(DescriptionLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(AlcoholVolumeLabel)
                        .addGap(37, 37, 37)
                        .addComponent(BrandLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(AlcoholVolumeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(BrandTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CreateButton)
                    .addComponent(CancelButton))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        AlcoholVolumeLabel.setVisible(false);
        BrandLabel.setVisible(false);
        AlcoholVolumeTextField.setVisible(false);
        BrandTextField.setVisible(false);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CancelButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CancelButtonMouseClicked
        dispose();
    }//GEN-LAST:event_CancelButtonMouseClicked

    private void CreateButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CreateButtonMouseClicked
        Category cat = (Category) CategoryComboBox.getSelectedItem();
        if (cat.getType().equals("food")) {
            Food product = new Food();
            product.setName(NameTextField.getText());
            product.setDescription(DescriptionTextArea.getText());
            product.setCategory(cat);
            product.setPrice(Double.valueOf(PriceTextField.getText()));
            product.setId(productDao.save(product));
            BarFrame.productModel.addElement(product);
        } else if (cat.getType().equals("beverage")) {
            Beverage product = new Beverage();
            product.setName(NameTextField.getText());
            product.setDescription(DescriptionTextArea.getText());
            product.setCategory(cat);
            product.setPrice(Double.valueOf(PriceTextField.getText()));
            product.setBrand(BrandTextField.getText());
            product.setAlcoholVolume(Double.valueOf(AlcoholVolumeTextField.getText()));
            product.setId(productDao.save(product));
            BarFrame.productModel.addElement(product);
            
        }
        dispose();
    }//GEN-LAST:event_CreateButtonMouseClicked

    private void CategoryComboBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_CategoryComboBoxItemStateChanged
        Category category = (Category) CategoryComboBox.getSelectedItem();
        if(category.getType().equals("beverage")){
            AlcoholVolumeLabel.setVisible(true);
            AlcoholVolumeTextField.setVisible(true);
            BrandLabel.setVisible(true);
            BrandTextField.setVisible(true);
        }
        else{
            AlcoholVolumeLabel.setVisible(false);
            AlcoholVolumeTextField.setVisible(false);
            BrandLabel.setVisible(false);
            BrandTextField.setVisible(false);
        }
    }//GEN-LAST:event_CategoryComboBoxItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProductCreateFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProductCreateFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProductCreateFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProductCreateFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProductCreateFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AlcoholVolumeLabel;
    private javax.swing.JTextField AlcoholVolumeTextField;
    private javax.swing.JLabel BrandLabel;
    private javax.swing.JTextField BrandTextField;
    private javax.swing.JButton CancelButton;
    private javax.swing.JComboBox<Category> CategoryComboBox;
    private javax.swing.JLabel CategoryLabel;
    private javax.swing.JButton CreateButton;
    private javax.swing.JLabel DescriptionLabel;
    private javax.swing.JTextArea DescriptionTextArea;
    private javax.swing.JLabel NameLabel;
    private javax.swing.JTextField NameTextField;
    private javax.swing.JLabel PriceLabel;
    private javax.swing.JTextField PriceTextField;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
