/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.eyse360.gui;

import com.eyse360.controllers.mysql.CategoryDAO;
import com.eyse360.controllers.mysql.ProductDAO;
import com.eyse360.models.Bar;
import com.eyse360.models.Category;
import com.eyse360.models.Check;
import com.eyse360.models.Product;
import com.eyse360.models.Table;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;

/**
 *
 * @author Erel
 */
public class SelectProductFrame extends javax.swing.JFrame {

    private Bar currentBar;
    
    private DefaultComboBoxModel comboboxModel;
    private DefaultListModel defaultListModel;
    private static CategoryDAO catDao;
    private static ProductDAO productDao;
    /**
     * Creates new form AddCategoryTOTable
     */
    public SelectProductFrame(Table table, Bar bar, Check check) {
        catDao = new CategoryDAO();
        productDao = new ProductDAO();
        currentBar = bar;
        
        initComponents();
        
        comboboxModel = new DefaultComboBoxModel();
        CategoryComboBox.setModel(comboboxModel);
        comboboxModel.addAll(catDao.getAllByBar(bar));
        
        defaultListModel = new DefaultListModel();
        ProductList.setModel(defaultListModel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CategoryComboBox = new javax.swing.JComboBox<>();
        CategoriesLabel = new javax.swing.JLabel();
        ProductListLabel = new javax.swing.JLabel();
        SelectButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        ProductList = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        CategoryComboBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                CategoryComboBox›temStateChanged(evt);
            }
        });

        CategoriesLabel.setText("Categories");

        ProductListLabel.setText("Product List");

        SelectButton.setText("Select");
        SelectButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SelectButtonMouseClicked(evt);
            }
        });

        ProductList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(ProductList);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(165, 165, 165)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SelectButton)
                    .addComponent(CategoriesLabel)
                    .addComponent(CategoryComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ProductListLabel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(CategoriesLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CategoryComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(ProductListLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SelectButton)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SelectButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SelectButtonMouseClicked
        Product product = ProductList.getSelectedValue();
        TableContentFrame.currentCheck.addProduct(product, 1);
        TableContentFrame.tableModel.fireTableDataChanged();
        dispose();
    }//GEN-LAST:event_SelectButtonMouseClicked

    private void CategoryComboBox›temStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_CategoryComboBox›temStateChanged
        Category category = (Category) CategoryComboBox.getSelectedItem();
        defaultListModel.addAll(productDao.getAllByBarAndCategory(currentBar, category));
    }//GEN-LAST:event_CategoryComboBox›temStateChanged

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CategoriesLabel;
    private javax.swing.JComboBox<Category> CategoryComboBox;
    private javax.swing.JList<Product> ProductList;
    private javax.swing.JLabel ProductListLabel;
    private javax.swing.JButton SelectButton;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
